
CREATE DATABASE IF NOT EXISTS QuanLyBanHang;

USE QuanLyBanHang;

# Table Customer
CREATE TABLE IF NOT EXISTS `Customer` (
cID BIGINT PRIMARY KEY,
cName VARCHAR(50) NOT NULL,
cAge TINYINT NOT NULL
);

# Table Product
CREATE TABLE IF NOT EXISTS `Product` (
pID BIGINT PRIMARY KEY,
pName VARCHAR (50) NOT NULL,
pPrice INT NOT NULL
);

# Table Order
CREATE TABLE IF NOT EXISTS `Order` (
oID BIGINT PRIMARY KEY,
cID BIGINT,
oDate DATETIME,
oTotalPrice TINYINT,
FOREIGN KEY (cID) REFERENCES  Customer(cID)
);

# Table Order Detail
CREATE TABLE IF NOT EXISTS `OrderDetail` (
odQTY INT,
oID BIGINT,
pID BIGINT,
FOREIGN KEY (oID) REFERENCES  `Order`(oID),
FOREIGN KEY (pID) REFERENCES  `Product`(pID)
);

